name: Linter

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Lint
        run: hatch run lint:all
