# TODO coverage
name: Testing

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Test
        run: hatch test --all --parallel
